### PR TITLE
[EE-211] Disable all interaction with workers set

### PR DESCRIPTION
**Pull request by michaelherold**
We don't need to track what workers are running on an instance, so disable it in the version that runs on instances.

### CODE REVIEW

**Review by bethanyhaubert — APPROVED** [review]
🍔  omg  `redis.sadd` 😭

**Review by danfitch — APPROVED** [review]
LGTM

**Review by andypeters — APPROVED** [review]
🎱

**Review by noecker — APPROVED** [review]
LGTM. Excited about getting this rolled out for so many reasons. Stabilizing Redis issues is huge, but also bringing overseas servers online becomes faster, since those servers don't have to run 19000 requests with cross-ocean latencies just to bring Resque up.

**Pull request merged**
